### ISSUE TITLE
Wrong Photo When Pressing Show ID

### ISSUE THREAD

**Issue by hgg022** [GMA950/jsfour-idcard#5]
When a player shows his own ID to another one, the informations are right, but the photo is not. I already tried to fix this issue on my own but i can't figure out how to do this, can you do it for us or, at least, if you can't for some reason, give us a tip on how to fix? If you want to contact me on discord my username is: hgg022#2122, it would be amazing if you could fix this. Thanks

**Comment by hgg022** [comment]
Fixed it!!!It was pretty hard to do tbh but i figured out!

**Comment by Itzmezzzzz** [comment]
> When a player shows his own ID to another one, the informations are right, but the photo is not. I already tried to fix this issue on my own but i can't figure out how to do this, can you do it for us or, at least, if you can't for some reason, give us a tip on how to fix? If you want to contact me on discord my username is: hgg022#2122, it would be amazing if you could fix this. Thanks

Hey how did you fixed that!? can you help me with this!
